apiVersion: v1
kind: Service
metadata:
  name: service-client
spec:
  selector:
    app: service-client
  type: NodePort
  ports:
    - name: http
      port: 8082
      nodePort: 30002

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-client
spec:
  selector:
    matchLabels:
      app: service-client
  replicas: 1
  template:
    metadata:
      labels:
        app: service-client
    spec:
      containers:
        - name: server
          image: 4321id1234/service-client
          ports:
            - name: http
              containerPort: 8082

---